GET /shifts # Get shifts

PUT /shifts # Creation of a shift

{
"begintime": "...",
"endtime": "...",
}


DELETE /shifts?shiftid=<int>





POST /shifts # Update shift


{
"shiftid": int,
"begintime": new UTC ISO 8601 datetimestring,
"endtime": new/old UTC ISO 8601 datetimestring,
"dayforceplanned": new/old boolean

}
